name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Buildozer
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip zlib1g-dev
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug
        mkdir apk
        cp bin/*.apk apk/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: question-search
        path: apk/*.apk